baseURL = "https://anthealiles.github.io/awesome-it-review/"
languageCode = "fr-fr"
title = "Awesome IT Review"

[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.highlight]
    style = "monokai"
  [markup.goldmark.renderer]
    unsafe = true
  [markup.org]
    enable = true
